"model":
  "d_model": 256
  "n_head": 4
  "d_head": 64
  "dropout": 0.1
  "d_ff": 1024
  "layernorm_epsilon": 1.e-12
  "n_layer": 3
  "n_seq": 256
  "n_vocab": 0
  "i_pad": 0
"vocab":
  "ko": "korean_english_news_ko_32000.model"
  "en": "korean_english_news_en_32000.model"
"data":
  "train": "korean_english_news_train_32000.json.zip"
  "dev": "korean_english_news_dev_32000.json.zip"
  "test": "korean_english_news_test_32000.json.zip"
  "src": "ko"
  "dst": "en"
"schedule":
  "name": "InverseSquareRootSchedule"
  "d_model": 256
  "warmup_steps": 4000
"optimizer":
  "name": "Adam"
  "beta_1": 0.9
  "beta_2": 0.98
  "epsilon": 1.e-9
